name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ•Ÿ Checkout
        uses: actions/checkout@v4

      - name: ğŸ–² Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: ğŸeŸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: ğŸeŸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: "${ { secrets.EXPO_TOKEN } }"

      - name: ğŸš‘ Install dependencies
        run: pnpm install

      - name: ğŸ–­ Build APK
        run: eas build --platform android --profile production --non-interactive